spring:
  application:
    name: dashlines-news-service
server:
  port: 8097
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true